# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [11]:
### [your code here]
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [12]:
### [your code here]
print(np.__version__ ) # Version
print(np.show_config)   # Configuration


1.24.3
<function show at 0x0000014302FCD620>


In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [14]:
### [your code here]
a = np.random.rand(2,3,5)
a1 = np.random.random((2,3,5))
a2 = np.random.randint(2,3,5)
a3 = np.random.randn(2,3,5)
#print(a)
#print(a1)
#print(a2)
print(a3)



[[[ 1.03453883  0.86220004  1.5180017   0.07479054  0.0563489 ]
  [-0.71614037  0.32000068 -0.22803367  0.13570462 -0.06878828]
  [ 1.10560077  0.29238879 -0.56085943 -0.2137864  -0.0780387 ]]

 [[-1.82788864 -0.16099972  0.96706931 -1.07585738  1.68697687]
  [-1.0259493   1.0190101  -0.59072551  0.49053974 -0.34926661]
  [-0.04058416 -1.02188729  1.9891519   1.38516603  1.0295095 ]]]



### 4. Print a.


In [15]:
### [your code here]
print(a)


[[[0.47956706 0.00153271 0.82261464 0.99065886 0.69698726]
  [0.99179987 0.71616745 0.46377626 0.89051175 0.56348689]
  [0.43937923 0.43447615 0.65130721 0.79863778 0.96182595]]

 [[0.21664478 0.14012084 0.22263437 0.99876599 0.96297795]
  [0.09470367 0.10680392 0.60953884 0.01350807 0.35128084]
  [0.86724251 0.43724524 0.74939485 0.72368735 0.33638998]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [16]:
### [your code here]
b = np.full((5,2,3),1)




### 6. Print b.


In [17]:
### [your code here]
print(b)


[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [18]:
### [your code here]
print(f"size of a and b are equal {a.size == b.size}")


size of a and b are equal True



### 8. Are you able to add a and b? Why or why not?


In [19]:
### [your code here]
np.add(a+b) # It is not possible because both arrays have different shape

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [20]:
### [your code here]
c = b.reshape(2,3,5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [21]:
### [your code here]
d = np.add(a,c)
print(d) # Now it gives result because both arrays have same shape


[[[1.47956706 1.00153271 1.82261464 1.99065886 1.69698726]
  [1.99179987 1.71616745 1.46377626 1.89051175 1.56348689]
  [1.43937923 1.43447615 1.65130721 1.79863778 1.96182595]]

 [[1.21664478 1.14012084 1.22263437 1.99876599 1.96297795]
  [1.09470367 1.10680392 1.60953884 1.01350807 1.35128084]
  [1.86724251 1.43724524 1.74939485 1.72368735 1.33638998]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [23]:
### [your code here]
print(f"array a {a}")
print(f"array d {d}")

# similarity -- both have same shape
#difference-- Values of elements in array a is between 0 to 0.99 (approx)
#difference-- Values of elements in array d is between 1 to 1.99 (approx)




array a [[[0.47956706 0.00153271 0.82261464 0.99065886 0.69698726]
  [0.99179987 0.71616745 0.46377626 0.89051175 0.56348689]
  [0.43937923 0.43447615 0.65130721 0.79863778 0.96182595]]

 [[0.21664478 0.14012084 0.22263437 0.99876599 0.96297795]
  [0.09470367 0.10680392 0.60953884 0.01350807 0.35128084]
  [0.86724251 0.43724524 0.74939485 0.72368735 0.33638998]]]
array d [[[1.47956706 1.00153271 1.82261464 1.99065886 1.69698726]
  [1.99179987 1.71616745 1.46377626 1.89051175 1.56348689]
  [1.43937923 1.43447615 1.65130721 1.79863778 1.96182595]]

 [[1.21664478 1.14012084 1.22263437 1.99876599 1.96297795]
  [1.09470367 1.10680392 1.60953884 1.01350807 1.35128084]
  [1.86724251 1.43724524 1.74939485 1.72368735 1.33638998]]]



### 12. Multiply a and c. Assign the result to e.


In [24]:
### [your code here]
e = np.multiply(a,c)
e


array([[[0.47956706, 0.00153271, 0.82261464, 0.99065886, 0.69698726],
        [0.99179987, 0.71616745, 0.46377626, 0.89051175, 0.56348689],
        [0.43937923, 0.43447615, 0.65130721, 0.79863778, 0.96182595]],

       [[0.21664478, 0.14012084, 0.22263437, 0.99876599, 0.96297795],
        [0.09470367, 0.10680392, 0.60953884, 0.01350807, 0.35128084],
        [0.86724251, 0.43724524, 0.74939485, 0.72368735, 0.33638998]]])



### 13. Does e equal to a? Why or why not?


In [25]:
### [your code here]
np.array_equal(e, a)
#They are equal because e is multiplication of a with identity matrix 



True



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [26]:
### [your code here]
d_max = np.max(d)
print(f"Max value in d {d_max}")

d_min = np.min(d)
print(f"Min value in d {d_min}")

d_mean = np.mean(d)
print(f"Mean value in d {d_mean}")





Max value in d 1.9987659944601166
Min value in d 1.0015327097182687
Mean value in d 1.557788942431818



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [27]:
### [your code here]
f = np.empty((2,3,5))





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [35]:
d.shape[1]

3

In [ ]:
### [your code here]
f = np.where(((d>d_min) & (d <d_mean)),25,f)
#np.where((d>d_min and d <d_mean),25)
#print(f)

#d_min = np.min(d)  # Ensure scalar value
#d_max = np.max(d)  # Ensure scalar value
#d_mean = np.mean(d)  # Ensure scalar value
for i in range(2):
    for j in range(3):
        for k in range(5):
            value = d[i,j,k]
            if d_min < value < d_mean:
                f[i, j, k] = 25
            elif value == d_mean:
                f[i, j, k] = 50
            elif d_mean < value < d_max:
                f[i, j, k] = 75
            elif value == d_min:
                f[i, j, k] = 0
            elif value == d_max:
                f[i, j, k] = 100
    print(f)            


[[[ 25.   0.  75.  75.  75.]
  [ 75.  75.  25.  75.  75.]
  [ 25.  25.  75.  75.  75.]]

 [[ 25.  25.  25. 100.  75.]
  [ 25.  25.  75.  25.  25.]
  [ 75.  25.  75.  75.  25.]]]
[[[ 25.   0.  75.  75.  75.]
  [ 75.  75.  25.  75.  75.]
  [ 25.  25.  75.  75.  75.]]

 [[ 25.  25.  25. 100.  75.]
  [ 25.  25.  75.  25.  25.]
  [ 75.  25.  75.  75.  25.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [43]:
### [your code here]
d = np.array(([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]))


d_min = np.min(d)  # Ensure scalar value
d_max = np.max(d)  # Ensure scalar value
d_mean = np.mean(d)  # Ensure scalar value
for i in range(2):
    for j in range(3):
        for k in range(5):
            value = d[i,j,k]
            if d_min < value < d_mean:
                f[i, j, k] = 25
            elif value == d_mean:
                f[i, j, k] = 50
            elif d_mean < value < d_max:
                f[i, j, k] = 75
            elif value == d_min:
                f[i, j, k] = 0
            elif value == d_max:
                f[i, j, k] = 100
    print(f)    



[[[ 75.  75.  75.  25.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 75.  25.  75.  75.  75.]]

 [[ 25.  25.  25. 100.  75.]
  [ 25.  25.  75.  25.  25.]
  [ 75.  25.  75.  75.  25.]]]
[[[ 75.  75.  75.  25.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 75.  25.  75.  75.  75.]]

 [[ 25.  25.  25.  25. 100.]
  [ 75.  75.  75.  75.  75.]
  [ 25.  75.   0.  75.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [46]:
### [your code here]
d = np.array(([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]))


f = np.empty(d.shape, dtype=object)        


d_min = np.min(d)  # Ensure scalar value
d_max = np.max(d)  # Ensure scalar value
d_mean = np.mean(d)  # Ensure scalar value
for i in range(2):
    for j in range(3):
        for k in range(5):
            value = d[i,j,k]
            if d_min < value < d_mean:
                f[i, j, k] = "B"
            elif value == d_mean:
                f[i, j, k] = "C"
            elif d_mean < value < d_max:
                f[i, j, k] = "D"
            elif value == d_min:
                f[i, j, k] = "A"
            elif value == d_max:
                f[i, j, k] = "E"
print(f)    



[[['D' 'D' 'D' 'B' 'D']
  ['D' 'D' 'B' 'B' 'B']
  ['D' 'B' 'D' 'D' 'D']]

 [['B' 'B' 'B' 'B' 'E']
  ['D' 'D' 'D' 'D' 'D']
  ['B' 'D' 'A' 'D' 'D']]]
